fos_user:
    db_driver: orm
    firewall_name: main
    user_class: App\Entity\Utilisateur
    from_email:
        address: "%env(MAILER_FROM_ADDRESS)%"
        sender_name: "%env(MAILER_FROM_NAME)%"
    registration:
        confirmation:
            enabled: true
    service:
        mailer: fos_user.mailer.twig_swift